### ISSUE TITLE
first Input for email configuration

### ISSUE THREAD

**Issue by BionStt** [EdiWang/Moonglade#121]
hai Edi,
i use your source code to learning to create blog for myself. i got some error.
its about encryption.
please check. first time Email configuration, i see that password not encrypt. 

thank you
![test1](https://user-images.githubusercontent.com/43228630/57008838-1f825f80-6c1d-11e9-90d7-4deb605e3782.jpg)

**Comment by EdiWang** [comment]
Hi @BionStt 

What do you mean by "first time"? Are you saying the first run of the system when SmtpPassword is not ever been set in the database? What's the reproduce steps?

Also, please try use "dev" branch to see if it is still an issue, because I just update that part of code few minutes ago.

**Comment by EdiWang** [comment]
@BionStt 

If you are in the first run of the blog system. The password will be initialized by default as an empty string in the database (BlogConfiguration table). It is by design. Or the blog will try to decrypt an empty string which will throw exception. 

You need to set the password in "/admin/settings/email-settings" along with other email settings.

**Comment by BionStt** [comment]
okay .. thank you...
