### ISSUE TITLE
Logger is null when I start this project.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#263]
![image](https://user-images.githubusercontent.com/19531547/65959753-6c48bb80-e485-11e9-97ca-08e2049f1043.png)

**Comment by EdiWang** [comment]
This is caused by .NET Core 3.0 upgrade, as mentioned in Microsoft docs: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0

> Writing logs before completion of the DI container setup in the Startup.ConfigureServices method is not supported:

> Logger injection into the Startup constructor is not supported.
> Logger injection into the Startup.ConfigureServices method signature is not supported
The reason for this restriction is that logging depends on DI and on configuration, which in turns depends on DI. The DI container isn't set up until ConfigureServices finishes.

> Constructor injection of a logger into Startup works in earlier versions of ASP.NET Core because a separate DI container is created for the Web Host. For information about why only one container is created for the Generic Host, see the breaking change announcement.

**Comment by EdiWang** [comment]
@Anduin2017 Fixed in #268 

不解决问题，而解决提出问题的logger. 微软砍，我也跟着砍~
