### ISSUE TITLE
Icon request for the following service providers.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#314]
![image](https://user-images.githubusercontent.com/19531547/70632501-e78ad280-1c69-11ea-8ff8-9e0185d6345e.png)

I really can't find the best way to insert icons here. I don't want to download the entire font-awesome.css. Seems the only way for me is to open an new issue here.

Please consider adding more service provider icons in the library. Thanks!

**Comment by EdiWang** [comment]
This needs discussion. I don't want to make the icon library big and heavy. The very first reason I switched from font-awesome to my own icons is that font-awesome consumed too much for network loading. I don't want to repeat the path. Let's find a more reasonable way rather than simply adding icons into the existing library.

**Comment by EdiWang** [comment]
Icons except for Bilbili were added in a recent release.
