### ISSUE TITLE
Feature request: Upload a file to my blog.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#410]
For example, I am writing a tutorial about how to create an Angular app.

And I want to put my built dist to the beginning of the article.

I may want a button that I can select and upload any kind of file to the blob, and get the URL of the CDN for the file, and insert a link to the article. So I can share files in my blog easily.

**Comment by EdiWang** [comment]
Moonglade's ancestor 'Felwood' used to have such a file upload and management feature 8 years ago. But was removed since:

- Large files: Different web servers and firewall products treat request size limitation differently. It's out of control for our code. 
- Domain and IP blacklist for file downloads: Some organizations, like mine and a lot other business in tech industries whose users are very likely programmers that visits Moonglade, they have strict firewall rules that blocks file downloads from untrusted domains, hosting a file share by Moonglade itself is usually blocked.
- CDN can cause you 'rich enough': If your file are large enough, attackers can request them like DDOS to dry your wallet. Some CDN are charged by file size, some CDN are charged by file counts. It depends.

So using a third party solution is by far the most reasonable way to share files on Moonglade.
Share files by GitHub, OneDrive, Dropbox are much better comparing to using the blog itself because:
- You can share files not only within the blog, but also to every other platforms
- They have their own infrastructure like CDN to make the download experience better
- They have advanced file management capabilities like versioning, deletion restore, permissions, etc
