### ISSUE TITLE
Memory Spike when using local account for login (使用本地登录时内存暴增)

### ISSUE THREAD

**Issue by jchhh912** [EdiWang/Moonglade#527]
Hi，我使用Moonglade作为我的博客和学习.net core，我发现在使用本地登录时发现有些时候内存会突然暴增，如下图：

![BUG2](https://user-images.githubusercontent.com/54928439/107326878-26731d00-6ae7-11eb-9cab-0e0dda8c940e.JPG)

通过断点不断尝试复原问题，在HashPassword方法中我看到出现这个异常，因为在执行这个之后他就出现了内存暴增的现象
![bug1](https://user-images.githubusercontent.com/54928439/107327025-60dcba00-6ae7-11eb-89b7-89a89299dc05.JPG)

尝试了一番，还是没搞明白，只好来请教大佬，谢谢！👀

**Comment by EdiWang** [comment]
1. The memory spike is a normal behavior when using Visual Studio to debug .NET Core applications because you are using DEBUG build, it's not representing any real problem, you will find this phenomenon in other projects as well, this is not an issue. If you truly want to find memory leaks, you should use memory profilers and take process dumps under RELEASE build.

2. The exception looks like when you are debugging this method, after it finished execution, you inspected `sha.Hash` once again, because at this time the function is already finished, your watch for `sha.Hash` will certainly fail. It's not a real runtime exception. If you want to know if there is any CLR exception going on when running the code, you should watch the Events graph for any Red dots, and then inspect them in Events tab below.

![image](https://user-images.githubusercontent.com/3304703/107343499-57118180-6afc-11eb-8861-b5f9a0af7ff7.png)

**Comment by jchhh912** [comment]
Thanks a lot!
