### ISSUE TITLE
[Feature request] Floating catalog

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#666]
Hi,

When the viewer is reading a long blog, he may need a brief catalog.

For example, in this article:

https://blog.fatedier.com/2020/07/22/k8s-pod-directional-migration/

It was really complicated. But there is always a floating catalog like this:

![image](https://user-images.githubusercontent.com/19531547/183880770-2180e240-c28a-413d-9f38-d2daf0cc8d72.png)

And clicking the catalog can easily jump inside the article.

It will significantly improve the reading experience for viewers!

**Comment by EdiWang** [comment]
This feature can be delivered in 2 phases, in order to make sure I still have something to do in the future.

- Phase 1: Only use anchor links on title elements set by the user when editing post, the user will have to switch to code editing in the rich editor. 
- Phase 2: Extract all title elements, add anchor links to those that wasn't added by the user.

**Comment by EdiWang** [comment]
Good request. I am working 996 to implement this feature.
