### ISSUE TITLE
Add a possibility to show count of views

### ISSUE THREAD

**Issue by saigkill** [EdiWang/Moonglade#834]
**Describe the bug**
To see, what content is read mostly, it would be good to have a view inside the Admin panel.

**Comment by EdiWang** [comment]
The ability of counting post views and likes, including most read posts were removed a year ago in v13.x, due to the fact that Moonglade could not have a precise tracking by it's own. Modern thirty party solutions can precisely identify real human users from bots and spiders because they have commercial grade risk databases, these are something Moonglade could not achieve at this moment.

To get a statistics of your page views, please use third party plugins, for example, my blog is using Microsoft Clarity. You could try Google Analytics, etc.
