### ISSUE TITLE
idea: Move from bootstrap-icons to fontawesome

### ISSUE THREAD

**Issue by saigkill** [EdiWang/Moonglade#841]
Because we now have support for social links, it could be helpful, if we move from bootstrap-icons to fontawesome. It has more icons to use.

**Comment by EdiWang** [comment]
Moonglade had used FontAwesome in the past a few years ago, it was too heavy, which took the majority of a network resource consumption in a single session. 

At that time, Moonglade is using webfont to display icons, which is still this way today. In this case, user must download the entire font library even there is only a few icons on the page.  

95% visitors of a typical Moonglade system comes from Google search, they only view a blog post and leave the site, so Moonglade is designed to be as lite as possible for a single post view, which mean transfer as few data as possible to the client. Data shows FontAwesome is affecting users in this way. So the decision was made to use bootstrap-icons instead of FontAwesome .

The possible way of getting a much larger icon library without affecting performance will be switching to SVG icons. Then users could only download the icons they need instead of a entire library.

This GitHub issue will not be fixed, but it's a good starting point for considering SVG migration. Thanks.
